name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Reference the GitHub secret

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11  # You can change the Python version

      - name: Run Python script
        run: |
          # Load the API key from the environment variable
          export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          python app.py 
